### ISSUE TITLE
Extent EditorParser Plugin to configure AutoFields

### ISSUE THREAD

**Issue by guischulz** [SWM-IT/qgis-netze-gas#4]
- Automatically set the AutoField configuration for fields "geändert von", "geändert am", "erfasst von", "erfasst am".
- Find out the location of the saved AutoField configuration and analyse a possible way to distribute it together with the project file

**Comment by JanGerste** [comment]
Edited documentation with Import function;
deleted mention of "erfasst_" values since those got moved to core QGIS layer default values.

Added .json file of exported AutoFields

**Comment by guischulz** [comment]
The auto field plugin uses the Qt class QSettings to save its configuration. Depending on the platform Qsettings stores settings at different locations, c.f. http://doc.qt.io/qt-4.8/qsettings.html#platform-specific-notes
Instead of tampering the settings directly we use the standard import/export functionality of the auto field plugin.
